use_clean_band_names = true

users = %W{
  ben
  bryan
  derek
  hunter
  jake
  jen
  jon
  jonm
  kyle
  neal
  peter
  sarah
  sheehan
  stirling
  tania
  tom
}

puts "Creating #{users.count} users"
users.each do |user|
  next if User.find_by_username(user).present?

  file_path = File.join(Rails.root, "db/seed_pictures", "#{user}.jpg")
  User.create(username: user, name: user.capitalize, password: user, picture: File.open(file_path))
end

if use_clean_band_names
  bands = [
    "Fear Is the Path to the Dark Side", # Source: http://rateyourmusic.com/list/monocle/band_names_that_are_ridiculously_long/
    "My Life With the Thrill Kill Kult",
    "Fear Before the March of Flames",
    "The Pains of Being Pure at Heart",
    "Shadowy Men on a Shadowy Planet",
    "This Is a Process of a Still Life",
    "Anderson Bruford Wakeman Howe",
    "Dave Dee, Dozy, Beaky, Mick & Tich",
    "Here Are the Facts You Requested",
    "Negligent Collateral Collapse",
    "I Would Set Myself on Fire for You",
    "No Movement No Sound No Memories",
    "The Number Twelve Looks Like You",
    "Throw That Beat in the Garbagecan!",
    "Thinking Fellers Union Local 282",
    "My America Is Watching Tigers Die",
    "I Love You but I've Chosen Darkness",
    "They Came From the Stars I Saw Them",
    "Stop Coming to My House Prom Queen",
    "Orchestral Manoeuvres in the Dark",
    "Casiotone for the Painfully Alone",
    "God's Temple of Family Deliverance",
    "Suburban Kids With Biblical Names",
    "The First Person to See an Elephant",
    "The Plot to Blow Up the Eiffel Tower",
    "The Insult That Made a Man Out of Mac",
    "The Captain Matchbox Whoopee Band",
    "Thomas Jefferson Slave Apartments",
    "The Kilimanjaro Darkjazz Ensemble",
    "The Brady Bunch Lawnmower Massacre",
    "Seagull Screaming Kiss Her Kiss Her",
    "Dr. Buzzard's Original Savannah Band",
    "Dr. West's Medicine Show &amp; Junk Band",
    "The Mystic Astrologic Crystal Band",
    "Medicine Park All Boy Derelict Band",
    "Meanwhile Back in Communist Russia",
    "Bodies in the Gears of the Apparatus",
    "The Accident That Led Me to the World",
    "To Separate the Flesh From the Bones",
    "Youthmovie Soundtrack Strategies",
    "The Disposable Heroes of Hiphoprisy",
    "The Voluptuous Horror of Karen Black",
    "The Darkest of the Hillside Thickets",
    "Stereophonic Space Sound Unlimited",
    "Roto Rooter Good Time Christmas Band",
    "The West Coast Pop Art Experimental Band",
    "An Experiment on a Bird in the Air Pump",
    "...And None of Them Knew They Were Robots",
    "The Strange Death of Liberal England",
    "Original Harmony Ridge Creek Dippers",
    "Someone Still Loves You Boris Yeltsin",
    "The Eighties Matchbox B-Line Disaster",
    "Ultrasonic Attack Wave Pest Repeller",
    "Youth Pictures of Florence Henderson",
    "I Can Lick Any Sonofabitch in the House",
    "I Can Make a Mess Like Nobody's Business",
    "...And You Will Know Us by the Trail of Dead",
    "The Tony Danza Tapdance Extravaganza",
    "Carter the Unstoppable Sex Machine",
    "Bloodsucking Zombies From Outer Space",
    "Barbarian Warriors in Search of Wisdom",
    "The Five Blind Boys of Mississippi",
    "First Dog to Visit the Center of the Earth",
    "Flowers from the Man Who Shot Your Cousin",
    "Mother Mallard's Portable Masterpiece Co.",
    "Please Inform the Captain This Is a Hijack",
    "Shut Your Eyes and You'll Burst Into Flames",
    "Total Sound Group Direct Action Committee",
    "Wreck Small Speakers on Expensive Stereos",
    "The Revolutionary Army of the Infant Jesus",
    "The Birds Are Spies, They Report to the Trees",
    "Triumph of Lethargy Skinned Alive to Death",
    "Up Up Down Down Left Right Left Right B A Start",
    "The Retaliation for What They Have Done to Us",
    "Success Will Write Apocalypse Across the Sky",
    "The Prayers and Tears of Arthur Digby Sellers",
    "The Presidents of the United States of America",
    "Flagitious Idiosyncrasy in the Dilapidation",
    "Acid Mothers Temple & the Melting Paraiso U.F.O.",
    "I Live the Life of a Movie Star Secret Hideout",
    "Professor Fuddle's Fantastic Fairy Tale Machine",
    "When People Were Shorter and Lived Near the Water",
    "I Wrote Haikus About Cannibalism in Your Yearbook",
    "Paracoccidioidomicosisproctitissarcomucosis",
    "Congratulations on Your Decision to Become a Pilot",
    "Composition of the Sensibilities of Melted Knowledge",
    "The Spectral Light &amp; Moonshine Firefly Snakeoil Jamboree",
    "The Powers of Darkness Shall Rain Blood Upon This City for 500 Years",
    "The Rock and Roll Dubble Bubble Trading Card Co. of Philadelphia 1941",
    "Gotye", # Source: http://www.elyrics.net/top/1.php
    "Adele",
    "One Direction",
    "Queen",
    "Maroon 5",
    "Justin Bieber",
    "Luke Bryan",
    "Carly Rae Jepsen",
    "Celine Dion",
    "Michael Jackson",
    "Kelly Clarkson",
    "Christina Perri",
    "Whitney Houston",
    "Emeli Sande",
    "Fun",
    "Little Big Town",
    "Katy Perry",
    "Taylor Swift",
    "Hunter Hayes",
    "Eric Church",
    "Birdy",
    "Nicki Minaj",
    "Lmfao",
    "Mercyme",
    "Omg Girlz",
    "Evanescence",
    "Tamela Mann",
    "Honey Singh",
    "Kip Moore",
    "Band Perry",
    "Beyonce",
    "Thompson Square",
    "Wanted",
    "Tangled",
    "Victorious",
    "Carrie Underwood",
    "Casting Crowns",
    "Miranda Lambert",
    "Pokemon",
    "Jessie J",
    "Bruno Mars",
    "Zac Brown Band",
    "Skillet",
    "Bella Thorne",
    "Melanie Fiona",
    "Train",
    "Christina Aguilera",
    "Drake",
    "Bon Jovi",
    "Lady Antebellum lyrics",
    "Slipknot",
    "Yeng Constantino",
    "Johnny Cash",
    "Martina McBride",
    "Bryant Oden",
    "Owl City",
    "3 Doors Down",
    "Linkin Park",
    "Sanctus Real",
    "Britt Nicole",
    "James Blunt",
    "Zendaya Coleman",
    "Coldplay",
    "Barenaked Ladies",
    "Rihanna",
    "J.r.a.",
    "Demi Lovato",
    "Ellie Goulding",
    "Mindless Behavior",
    "Chris Tomlin",
    "Pink",
    "Guns N' Roses",
    "David Guetta",
    "Josh Groban",
    "Maher Zain",
    "Kenny Loggins",
    "Eli Young Band",
    "Elena Siegman",
    "Anthony Hamilton",
    "Tim McGraw",
    "Rascal Flatts",
    "Jaron & The Long Road To Love",
    "Miley Cyrus",
    "Vince Gill",
    "Les Miserables",
    "Uncle Kracker",
    "Sidewalk Prophets",
    "Journey",
    "Enya",
    "Usher",
    "Jason Aldean",
    "Shinedown",
    "Wiz Khalifa",
    "Black Veil Brides",
    "Austin Mahone",
    "Louis Armstrong",
    "Frank Sinatra",
    "Billy Currington",
    "Sara Evans",
    "Rizzle Kicks",
    "JFKFC", # Source: http://www.pastemagazine.com/blogs/lists/2009/12/the-100-best-band-names-of-all-time.html
    "Camper Van Beethoven",
    "Kathleen Turner Overdrive",
    "Mary Tyler Morphine",
    "John Cougar Concentration Camp",
    "Gringo Star",
    "The Lee Harvey Keitel Band",
    "Natalie Portman's Shaved Head",
    "Propagandhi",
    "Gnarls Barkley",
    "X",
    "The The",
    "The Who",
    "The Band",
    "The Smiths",
    "Average White Band",
    "!!!",
    "The Names",
    "The Yeah Yeah Yeahs",
    "Question Mark and the Mysterians",
    "The Libertines",
    "The Pains of Being Pure at Heart",
    "The Clash",
    "Parliament Funkadelic",
    "One Bad Pig",
    "Morphine",
    "Southern Culture on the Skids",
    "The Bastard Sons of Johnny Cash",
    "Suburban Kids With Biblical Names",
    "De La Soul",
    "Throwing Muses",
    "Butthole Surfers",
    "Meat Puppets",
    "Paradise Vendors",
    "Sunny Day Real Estate",
    "Throbbing Gristle",
    "The Velvet Underground",
    "The Flaming Lips",
    "The Apples in Stereo",
    "Drive-By Truckers",
    "Talking Heads",
    "Betty's Not a Vitamin",
    "Someone Still Loves You Boris Yeltsin",
    "Get Cape. Wear Cape. Fly.",
    "Say Hi To Your Mom",
    "Be Your Own Pet",
    "I Am The World Trade Center",
    "Dogs Die in Hot Cars",
    "Dead Can Dance",
    "Follow For Now",
    "Pretty Girls Make Graves",
    "From The Vault",
    "Live From Hangout",
    "Song Premiere",
    "Live From Paste",
    "Megadeth",
    "Bloody Wall of Gore",
    "Motorhead",
    "Dead Kennedys",
    "Suicidal Tendencies",
    "Wiccan Guidance Counselor",
    "Sex Pistols",
    "The Brian Jonestown Massacre",
    "The Supremes",
    "The Jesus and Mary Chain",
    "Queen",
    "Supreme Beings of Leisure",
    "They Might Be Giants",
    "T. Rex",
    "Jesus Lizard",
    "Tenacious D",
    "40 Lb Head",
    "Thank God We're Immortal",
    "Super Furry Animals",
    "Echo & The Bunnymen",
    "Fuzzy Bunny Slippers",
    "Modest Mouse",
    "Startled Insects",
    "Local to Indianapolis",
    "The Rural Alberta Advantage",
    "Pixies",
    "The Replacements",
    "Black Moth Super Rainbow",
    "Japancakes",
    "The Dictatortots",
    "Swimming Pool Qs",
    "Hostile Comb-Over",
    "Alcoholocaust",
    "Abracadaver",
    "Pabst Smear",
    "Test Icicles",
    "Rumpleforeskin",
    "Furious George",
    "Dr. Teeth and the Electric Mayhem",
    "Guided By Voices",
    "Joy Division",
    "Led Zeppelin",
    "A Tribe Called Quest",
    "13th Floor Elevators",
    "Godspeed You! Black Emperor",
    "Public Enemy",
    "Man... or Astro-Man?",
    "We Were Promised Jetpacks!",
    "From The Vault",
    "Live From Hangout",
    "Song Premiere",
    "Live From Paste"
  ]
else
  # Source: http://sam.hochberg.com/bandname.html (which in turn was sourced from http://www.brightlightsfilm.com/weirdbandnames/)
  bands = [
    "A Box of Fish with Tartar Sauce",
    "A Boy Named Gomer",
    "Above Average Weight Band",
    "A Cat Born In An Oven Isn't a Cake",
    "Accidental Goat Sodomy",
    "Adickdid",
    "Adult Children of Heterosexuals",
    "Afghanistan Banana Stand",
    "Aggressive Crotch Display",
    "Agnes Morehead",
    "Aha, the Attack of the Green Slime Beast",
    "Albino Toilet Boys",
    "Alcoholocaust",
    "Alien Nymphos from Uranus",
    "Alien Sex Fiend",
    "Amberham Lincoln",
    "Amputatoe",
    "Anal Babes",
    "Anal Beard Barbers",
    "Anal Cunt",
    "Anal Sadist",
    "Ancient Chinese Penis",
    "An Emotional Fish",
    "Angry Samoans",
    "Anus the Menace",
    "Apocolypse Hoboken",
    "The Archbishop's Enema Fetish",
    "The Armadildoes",
    "Armageddon Dildos",
    "Armpit",
    "Arthur Loves Plastic",
    "Ashtray Boy",
    "The Ass Baboons of Venus",
    "Ass Ponys",
    "Ass Solvent",
    "Assuck",
    "Attila The Stockbroker",
    "Baby Shit Brown",
    "Badical Turbo Radness",
    "The Bad Livers",
    "Bad Mutha Goose",
    "Baldilocks",
    "Baloney Ponys",
    "The Band Formerly Known As Sausage",
    "A Band Named Bob",
    "Band Over",
    "Barbara's Bush",
    "Barbie Bones",
    "Barefoot Hockey Goalie",
    "Barenaked Ladies",
    "Barf",
    "Barnyard Slut",
    "Barney Rubble and the Cunt Stubble",
    "Barry White Boys",
    "Bassholes",
    "Bearded Clams",
    "Bearded Itchy Lover",
    "Beast Penis",
    "Beats the Hell Out of Me",
    "Beef Masters",
    "The Bendy Monsters",
    "Ben Wa and the Blue Balls",
    "Bertha Does Moosejaw",
    "Bertha's Mule",
    "Betty Ford",
    "Betty's Not a Vitamin",
    "Beverley Beer Bellies",
    "Biff Hitler and the Violent Mood Swings",
    "Big Ass Truck",
    "Big Balls and the Great White Idiot",
    "Big Black Nun",
    "Big Blow and the Bushwackers",
    "Big Daddy Cumbuckets",
    "Big Dead Fish",
    "Big Dick and the Extenders",
    "Big Fat Pet Clams From Outer Space",
    "Big Fish Ensemble",
    "Big In Iowa",
    "Big White Undies",
    "The Biggest Freak in New Jersey",
    "Bimbo Toolshed",
    "Bionic Roomate",
    "Birth Hole",
    "Bitter Enemies/Butter Enemas",
    "Bizarr Sex Trio [sic]",
    "Black Leather Agenda",
    "Black Leather Jesus",
    "Bleeding Rectum",
    "Blew Willie",
    "Bloated Scrotum",
    "Blonder Tongue",
    "Bloody Stools",
    "Blow Monkeys",
    "Blueballs Deluxe",
    "Boba Fett Youth",
    "Bobby Joe Ebola and the Children MacNuggits",
    "Body Falling Down Stairs",
    "Boiled Angel",
    "Bolt Upright and the Erections",
    "Bondage A Go Go",
    "Bonedaddys",
    "Bongwater",
    "Bongzilla",
    "Bordering On Retarded",
    "Boris the Sprinkler",
    "The Bourbon Tabernacle Choir",
    "BowWowWowHaus",
    "Bozo Porno Circus",
    "Brady Bunch Lawnmower Massacre",
    "Bright Blue Gorilla",
    "Buck Naked and the Bare Bottom Boys",
    "Bullwinkel Gandhi",
    "Brutal Juice",
    "Brutal Noodle",
    "Buck Satan and the 666 Shooters",
    "Buddy Wasisname and the Other Fellas",
    "Bulimia Banquet",
    "Bumgravy",
    "The Bumpin' Uglies",
    "Bunchoffuckingoofs",
    "Burger Pimp",
    "Buster Hymen & the Penetrators",
    "Butthole Surfers",
    "Butt Savages",
    "Buttsteak",
    "Butt Trumpet",
    "Caltransvestites",
    "Cancer Bunny",
    "Candy Striper Death Orgy",
    "Cap'n Crunch and the Cereal Killers",
    "Captain Drinking Binge",
    "Carnage Asada",
    "Cat Butt",
    "Cat Rapes Dog",
    "Carter the Unstoppable Sexmachine",
    "Cheetah Chrome Motherfuckers",
    "Cherry Coke Enema",
    "Cherry Poppin' Daddies",
    "Cher UK",
    "Chewbacca Plaid Cock",
    "Chia Pet",
    "The Chicken Charmers",
    "Chickens On Smack",
    "Chocolate Bunnies From Hell",
    "Christ On A Crutch",
    "Cindy Brady's Lisp",
    "Circle Jerks",
    "Clive Pig and the Hopeful Chinamen",
    "Clitaurus Rex",
    "Clown Meat",
    "Cobaine's Brains",
    "Cocknoose",
    "Coffin Break",
    "Colon On The Cob",
    "Colostomy Grab-Bag",
    "Cookie Mould and the Smegmettes",
    "The Couch Slugs",
    "Cortizone 5",
    "Crappy the Clown and the Punch Drunk Monkies",
    "Craven Morehead",
    "Crazy Taco Cafeteria",
    "Cream of Whoop-Ass Soup",
    "Crew Slut",
    "Crispy Ambulance",
    "Crocheted Doughnut Ring",
    "Crosseyed Chicken",
    "The Crucifucks",
    "Crybabies With Brassholes",
    "Cultivated Bimbo",
    "Cum Dumpster",
    "The Cunning Runts",
    "Cunts With Attitude",
    "Curious George and the Homophobes",
    "Cycle Sluts From Hell",
    "Dairy Queen Empire",
    "Damn the Bad Luck",
    "Dancing Cigarettes",
    "The Dancing French Liberals of 1848",
    "Dayglo Abortions",
    "Dead Fish Prophecy",
    "Dead Kennedys",
    "Dead Milkmen",
    "The Dead Pants (Die Toten Hosen)",
    "Deepthroat Shotgun",
    "Desciples of Ed",
    "Demon Barf",
    "Dick Cheese and the Crackers",
    "Dick Delicious and the Tasty Testicles",
    "Dick Duck and the Dorks",
    "The Dick Nixons",
    "Dickless",
    "The Dicks",
    "Dicky Retardo",
    "Did Lee Squat?",
    "Dildo Warheads",
    "Dirt Clod Fight",
    "Dirty Dick and the Trojan Test Pilots",
    "Dirty Girl Scout",
    "Disappointed Parents",
    "Disgruntled Postal Workers",
    "The Dismemberment Plan",
    "The Do I Look Like I Give a Fucks",
    "Dog Food Five",
    "Dogfuckers",
    "Doggy Style",
    "Dog Lips",
    "Dog Shit Rangers",
    "Dogs With Jobs",
    "Don Knotts Overdrive",
    "Dopper Cocks",
    "Doris Daze",
    "Douche Gimlet",
    "Downy Mildew",
    "Dracula Milk Toast",
    "Drag King",
    "Dragmules",
    "Draw Your Own Cow [Rita din egen ko]",
    "Dreaded Apparatus",
    "Drew Barrymore's Dealer",
    "Drive By Crucifixion",
    "Drive-In Funeral",
    "Drunks With Guns",
    "Dumpster Juice",
    "Dusty Cowshit",
    "Earthpig and Fire",
    "Eat My Afterbirth",
    "e. coli",
    "Edith Head",
    "Ed Gein's Car",
    "Ed's Redeeming Qualities",
    "Elastic Sausage",
    "Electric Blue Peggy Sue and the Revolutionions from Mars",
    "Electric Vomit",
    "The Elvis Diet",
    "Elvis and the Shitheads",
    "Elvis Hitler",
    "Emily's Sassy Lime",
    "End of Orgy",
    "Ethyl Meatplow",
    "Ethyl Merman",
    "Eve's Plumb",
    "Evil Weiner",
    "Experimental BBQ",
    "Exploding Boy",
    "Exploding Fuck Dolls",
    "Exploding Head Trick",
    "Exploding Tits",
    "Exploding White Mice",
    "Fabulous Pimps",
    "Facial Defecation",
    "Fag",
    "Fag Bash",
    "Fangboy and the Ghouls",
    "Farrt",
    "The Fartz",
    "The Fat Chick from Wilson Phillips",
    "Fat Luv",
    "Fearless Iranians From Hell",
    "The Fellatio Ratio",
    "Fetus Fajitas",
    "Fields of Shit",
    "The Fierce Nipples",
    "'57 Lesbian",
    "Five Fat Guys Who Rock",
    "Fix My Head",
    "The Flaming Donuts of Jesus",
    "Flaming Lips",
    "Flamin' Schnanuses",
    "Flatutory Rape",
    "Flavor of Uranus",
    "Flopping Bodybags",
    "Flying Dustbunnies",
    "Force Vomit",
    "Foreskin 500",
    "Four Honkies In a Big Black Car",
    "The 4-Skins",
    "Four Nurses of the Apocalypse",
    "The Freaky Executives",
    "The Fred Mertz Experience",
    "Free Beer",
    "Free Beer and Chicken",
    "Free Range Chicken",
    "The French are from Hell",
    "Freud Chicken",
    "Frogs Don't Cry",
    "Fromage d'Amour",
    "Fuck",
    "Fuckemos",
    "Fuckface",
    "Fuckhead",
    "Fucking Angels",
    "The Fucking Cunts",
    "Fuckin' Shit Biscuits",
    "Fuckin' Son of a Bitch",
    "Fuck Me, Suck Me, Call Me Helen",
    "Fuckshitpiss",
    "Fuck Your Stupid Civilization",
    "Fuck You Yankee Bluejeans",
    "Fudge Tunnel",
    "Full Throttle Aristotle",
    "Full Metal Chicken",
    "Full Metal Faggot",
    "The Funkin' Donuts",
    "Funman and the Scumbags",
    "Furious George",
    "Gag Factor",
    "GangGreen",
    "Gangrene",
    "Gangway Fathead",
    "Gaye Bikers on Acid",
    "Gee That's A Large Beetle I Wonder If It's Poisonous",
    "Geisha Balls",
    "Genitorturers",
    "The Glands of External Secretion",
    "Global Disrobal",
    "Glory Hole",
    "God's Girlfriend",
    "Goldfish Don't Bounce",
    "The Go Kill Yourselves",
    "Go Nad Go",
    "Gonoreagan",
    "Granny's Hole",
    "Grim Skunk",
    "Grand Mother Fucker",
    "Gregg Turner and the Blood Drained Cows",
    "Guess My Perversion [Gissa min perversion]",
    "Guitarantula",
    "Habitual Sex Offenders",
    "The Hair & Skin Trading Co.",
    "Hakan Sleeps Naked [Hakan Sover Naken]",
    "Half Man, Half Biscuit",
    "Halibutt Sharon",
    "Halo of Flies",
    "Hamster Sandwich",
    "Hard-drinkin' Housewives",
    "Hard-Ons",
    "Harry Palms and the Gym Towels",
    "Harry Pussy",
    "The Hate Fuck Trio",
    "Headless Marines",
    "Headlice",
    "Head Like a Hole?",
    "Heavy Into Jeff",
    "Heavy Pink Insulator",
    "Heavy Vegetable",
    "Helen Keller Plaid",
    "The Helicopter Barfs [Helikoptern kraeks]",
    "Hellacopter Meat",
    "Hell Camino",
    "Hell Toupee",
    "Hello I'm A Truck",
    "Henry Kissinger's Tits",
    "Here, Eat This!",
    "Her Majesty the Baby",
    "Hermaphrochrist",
    "The Hermaphrodaddies",
    "Herpes Cineplex",
    "He's Dead Jim",
    "Heterophobia",
    "Heywood Trout Festival",
    "Hindu Garage Sale",
    "Hitler Stole My Potato",
    "Hockey Teeth",
    "Hollow Chocolate Bunnies of Death",
    "Hollywood Chainsaw Hookers",
    "Holy Mary, Mother of Bert",
    "Hornets Attack Victor Mature",
    "Horny Hogs",
    "Horny Mormons",
    "The Horrid Farts",
    "Hot Rod Shopping Cart",
    "Hot Seamen",
    "House of Large Sizes",
    "Hugh Jorgan and the Four Skins",
    "The Humpers",
    "The Hurling Tandooris",
    "I Buried Paul",
    "If Cows Had Wings",
    "I Just Killed My Parents",
    "I Love My Shih-Tzu",
    "Immaculate Infection",
    "Impaled Nazarene",
    "Impotent Seasnakes",
    "Individual Fruit Pie",
    "The Inflatable Boy Clams",
    "The Inflatable Jesus Love Dolls",
    "Inhale Mary",
    "The Insult That Made a Man Out of Mac",
    "The Introspective Playboy",
    "Iowa Beef Experience",
    "I Played in Anal Spew",
    "Iron Liver",
    "Iron Prostate",
    "It's All Meat",
    "Jabbering Trout",
    "Jackie O Motherfucker",
    "Jack Off Jill",
    "The Jackofficers",
    "Jason's Cat Died",
    "Jazz Iguanas",
    "The Jean Paul Sartre Experience",
    "Jehovah's Waitresses",
    "Jehovah's Witness Protection Program",
    "Jenny's Pussy",
    "Jerry's Kids",
    "Jesus Christ and the Nailknockers",
    "Jesus Christ Super Fly",
    "Jesus Chrysler Supercar",
    "Jesus Fucking Christ",
    "JFKFC",
    "Jif and the Choosy Mothers",
    "Jim Jones and the Kool Aid Kids",
    "The Jizzbuckets",
    "Jizzy Speedwack",
    "Joan of Arkansas",
    "Jodie Foster's Army",
    "John Cougar Concentration Camp",
    "John Holmes: Cucumber Smuggler",
    "Johnny Jism",
    "Johnny McPenis and the Ass Clams",
    "Johnny Panic and the Bible of Dreams",
    "Johnny Uterus and the Fallopian Tubes",
    "Johnny Vomit",
    "Jolly Naked Fishermen",
    "Juggling Death Squad",
    "Kaka Pussy",
    "Kamakazi Sex Pilots",
    "Kathleen Turner Overdrive",
    "Kenfunky Fried",
    "Kerrigan's Knees",
    "Kick Ass Ernie",
    "Kid Bastard and the Strap-on Dicks",
    "Killer Kiwis",
    "Killer Pussy",
    "Kill Ted Knight",
    "King Fucker Chicken",
    "Kissing the Pink",
    "Knights of Butthole [Perseenreian Ritarit]",
    "Kung Fu Action Clergy Persons",
    "K.Y. and the Backsliders",
    "Lavay Smith and The Red Hot Skillet Lickers",
    "Lawnsmell",
    "The Leave It To Beaver Conehead Immolation",
    "Lee Harvey Keitel",
    "Lee Press-On and the Nails",
    "Lesbian Dopeheads on Mopeds",
    "Lesbian Ninjas",
    "Lip Smacking Kitten Lunch",
    "Lipstick Sandwich",
    "Lisa Gives Head",
    "Lord Panic and the Exploders",
    "Lorne Greene's Wet Nipple",
    "Love Gravy",
    "Lovebucket & Slapphappy Super-fly",
    "Lubricated Goat",
    "Lubricunts",
    "The Luminous Toilet Bowls",
    "Lung Mustard",
    "Luxury Christ",
    "Maggot Sandwich",
    "Ma Joad and the Load-Blowers",
    "Man...or Astro-Man?",
    "Manson-Nixon Line",
    "Mao Tse Helen",
    "Mary Carves the Chicken",
    "Mary Kay and the Cosmetics",
    "Mate/Spawn/Kill",
    "Mayhem Lettuce",
    "Me and My Right Hand",
    "Meat Beat Manifesto",
    "Meat Cigars",
    "Meatpipe",
    "Meat Puppets",
    "Meat Shits",
    "Meaty Pants",
    "Mechanical Tampon Fish",
    "Mega Smegma",
    "Men Among Poodles",
    "Menstrual Gravy",
    "Microwavable Tree Frogs",
    "Mighty Sphincter",
    "Mill Valley Taters",
    "Minnie Pearl Necklace",
    "Minnie Pearl's Jam",
    "Mr. Bill and the Cumtones",
    "Mr. Happy and the Genocides",
    "Mr. Quintron and the Flossy Unicorn Puppet Show",
    "Mr. Tasty and the Bread Healers",
    "Mr. T Experience",
    "Moist Fist",
    "Monkey Fucks Football",
    "The Morbid Tavern Apple Choir",
    "More Drunk Cowboys",
    "The Most Sordid Pies",
    "Mother Theresa's Children [Moder Theresas Barn]",
    "Mott the Hoople",
    "Mouse and the Traps",
    "Much Ado About Shit",
    "The Muffs",
    "Mussolini Headkick",
    "My Dad is Dead",
    "My Dog Has Hitler's Brain",
    "My Uncle's Asshole",
    "My White Bread Mom",
    "Naked Potato",
    "Nancy Reagan's Abortions",
    "Nasal Sex With Broken Glass",
    "Natural Fonzie",
    "Naugahyde Chihuahuas",
    "Nearly Died Laughing While Shaving My Butt",
    "Ned's Atomic Dustbin",
    "The Negro Problem",
    "New Squids on the Dock",
    "99th Fuck You",
    "Nip Drivers",
    "Nipple Erectors",
    "Nipple Hardness Factor",
    "Nocturnal Emissions",
    "Nomad Nipples",
    "Noodle Muffin and the Pig Squints",
    "Norman Bates and the Shower Heads",
    "Not Drowning, Waving",
    "Not With My Camel",
    "Nuclear Pope Sex Dolls",
    "Nurse With Wound",
    "Nuts Can Surf",
    "Octapussy",
    "Oedipussy",
    "1,200,000 Dead Tibetians",
    "1000 Homo DJs",
    "Organic Condom Mazda Drugs",
    "Out of Godzilla's Butt",
    "Out Vile Jelly",
    "Ovarian Trolley",
    "Ozzy Beard Spaghetti",
    "Pabst Smear",
    "Painful Discharge",
    "Painful Rectal Itch",
    "Paisley Brain Cells",
    "Pamper the Madman",
    "Pansy Division",
    "Part Time Christians",
    "Paul Minor's Great Big Ego",
    "Peace Love and Pitbulls",
    "Pearl Harbor and the Explosions",
    "Pee",
    "Pee Shy",
    "The Pee Tanks",
    "Pelvic Meatloaf",
    "Penis DeMilo",
    "Penis Flytrap",
    "Penis Pulling Ramrods of Death",
    "Penis Sheurekan",
    "Penis Your Majesty",
    "Penis Wrinkle",
    "People With Chairs Up Their Noses",
    "Peppermint Dildo",
    "Perforated Head",
    "Peter and the Test Tube Babies",
    "Phallus Dei",
    "Phenobarbidols",
    "Philemon Arthur and the Dung",
    "Phlegm Fatale",
    "Picadilly Circus People",
    "Pieces of Lisa",
    "Pimps of Venus",
    "Pink Slip Daddy",
    "Piss",
    "Pissed Officers",
    "Piss Factory",
    "The Pissflaps",
    "Piss Wizards",
    "Placenta Sandwich",
    "Planet of Pants",
    "Plastic Nude Martini",
    "Playdough Fish",
    "Poonanie Cramp-Up",
    "Poop Shovel",
    "Pope John Paul Quartet with Friends and Blowers on the Rocks",
    "Pope on a Stick",
    "Popemobile",
    "Pork Queen",
    "Pornhuskers",
    "Porn on the Cob",
    "Post Nasal Drip",
    "Poultry in Motion",
    "Pounded Clown",
    "Power of Pussy",
    "Power Snatch",
    "Pregnant Men",
    "Premature Ejaculation",
    "Premature Evacuation",
    "Pretentious Flamedogs",
    "Prick",
    "Princess Tinymeat",
    "Printed At Bismarck's Death",
    "Prison Rape Scenes",
    "Professor Morrison's Lollipop",
    "Psychic Buddist Gorillas",
    "Psycho Sluts from Hell",
    "Public Enema",
    "Puke Daisies",
    "Pumpin' Ethyl",
    "Pungent Frustration",
    "Pure Bastard Extract",
    "Purple Headed Love Warriors",
    "Purple Vulture Shit",
    "Pussy Crush",
    "Pussy Galore",
    "Pussy Tourette",
    "Radical Vulvetomy",
    "Raging Woodies",
    "Rainbow Butt Monkeys",
    "The Rampant Hedgehogs",
    "Rash of Stabbings",
    "Rats of Unusual Size",
    "Real Fucking Idiots",
    "Rebel Without Applause",
    "Recktum",
    "Rectal Nightmare",
    "Reluctant Stereotypes",
    "REO Speed Dealer",
    "Revolting Cocks",
    "Rhinohumpers",
    "Rhythm Method",
    "Roid Rogers and the Whirling Butt Cherries",
    "Rolling Donut",
    "Root Boy Slim and the Sex-Change Band with The Rootettes",
    "Rubber Nipple Salesmen",
    "Rudimentary Peni",
    "Rugburns",
    "Rump Rangers",
    "The Runz",
    "Quasimodo and the Eunuchs",
    "The Queers",
    "Queer Wookie",
    "Question Mark & the Mysterians",
    "Sam Esh & Hard Black Thing",
    "Sam's Butt",
    "Sandy Duncan's Eye",
    "Satan's Cheerleaders",
    "Satan's Cheese",
    "Satan's Penis",
    "Saturated Fat",
    "Saturday's Garbage",
    "Saturn Flea Collar",
    "Schlong",
    "Science Diet",
    "Scoring Dope for the Ultimate Woman",
    "Scraping Foetus Off the Wheel",
    "Screaming Brocolli",
    "Screaming Fucking Hippies",
    "Screaming Headless Torsos",
    "Screaming Moist Accountants",
    "Scrotum",
    "Septic Death",
    "7 Foot Spleen",
    "Seven Year Bitch",
    "Severe Tire Damage",
    "Sex Clark Five",
    "Sex With Midgets",
    "Sharon Stoned",
    "She Stole My Beer",
    "Sheep On Drugs",
    "Shirley Temple of Doom",
    "Shirley Temple Pilots",
    "The Shit",
    "Shit Bong",
    "Shit Birds",
    "Shit Dogs",
    "Shoot the Mime",
    "Shot Down In Ecuador, Jr.",
    "The Shower Scene from Psycho",
    "Shower With Goats",
    "Simulated Orgasms [Simulerte Orgasmer]",
    "Sinus Envy",
    "Sister Run Naked",
    "Six Inch Nipples",
    "6 Hard Brothers and a Dog",
    "69% Female",
    "Skadelic Smegma",
    "Skankin' Pickle",
    "Skinflick",
    "Skunk Death",
    "Slut Kitchen",
    "Sluts for Hire",
    "Small Ball Paul",
    "Smegma",
    "Smegma & the Nuns",
    "Smelly Tongues",
    "Smilin' Hams",
    "Smoking Popes",
    "Snatch",
    "Snatch Attack",
    "Snatches Of Pink",
    "Sniveling Shits",
    "Snot Rocket",
    "Snuff the Ficus",
    "Sodom & Gomorrah Liberation Front",
    "Softcocks",
    "Solosex",
    "Some Kind of Cream",
    "Soothing Sounds For Baby",
    "Sorry About Your Daughter",
    "Soul Coughing",
    "Spacecocks",
    "Space Hog",
    "Spaceman Bill and the Groovy Gravy",
    "Space Negroes",
    "Space Pussy",
    "Spanking Bishops",
    "Spastic Colon",
    "The Spastic Rats",
    "Speculum Fight",
    "Spermbirds",
    "Sperm Wails",
    "Spock's Johnson",
    "Spooky Tooth",
    "Sucking Diction",
    "Stale Urine",
    "*.fat [pronounced STAR DOT FAT]",
    "STD Police",
    "Stiff Richards",
    "Stiff Woodies",
    "Stinky Fire Engine",
    "St. Mucous",
    "Stop Calling Me Frank",
    "Straight Jacket Lucy",
    "Strangulated Beatoffs",
    "Strong, Naked & Car Thieves [Sterk, Naken & Biltyvene]",
    "Stud McCoy and the Creemy Twinkies",
    "Stukas Over Bedrock",
    "Sucking Chest Wound",
    "Super Sonic Soul Pimps",
    "Surfing Jesus",
    "The Surf Maggots",
    "Surgical Penis Klinik",
    "Susanne and the Guys With Ties",
    "Swallowing Shit",
    "Sweaty Nipples",
    "Swingin' Johnsons",
    "Swingin' Udders",
    "The Swinging Love Corpses",
    "Swollen Monkeys",
    "Tastes Like Chicken",
    "T-Bone and the Spit Vendors",
    "Technosquid Eats Parliament",
    "Ted Bundy's Volkswagen",
    "Ted Ed Fred",
    "Teenage Jesus and the Jerks",
    "Temporary Darkening of the Stool",
    "Testostertones",
    "Thank God We're Immortal",
    "The The",
    "The Very Idea of Fucking Hitler",
    "They Tried To Frame OJ",
    "They Were Expendable",
    "Thinking Fellers Union Local 282",
    "Third Global Vagina Torture",
    "This",
    "This Is Our Daughter",
    "This Is Serious, Mum",
    "Thomas Jefferson Slave Apartments",
    "3D House of Beef",
    "Throbbing Gristle",
    "Thurston Howell's Boner",
    "Tit Wrench",
    "Titty Bingo",
    "To Live and Shave in LA",
    "Toiling Midgets",
    "Tonto's Expanding Headband",
    "Too Fat to Skate",
    "Tortured Scrotum",
    "Toxic Shock and the Tampons",
    "Tracy & the Hindenburg Ground Crew",
    "Trailer Park Casanovas",
    "Traveling Dingleberries",
    "Trotsky Icepick",
    "Trout Fishing In America",
    "Tumor Circus",
    "Tupperware Death",
    "Two For Flinching",
    "Two Minute Sinatra",
    "2000 Flushes",
    "UFOFU",
    "Ugly Head",
    "Ultimate Spinach",
    "Unidentified Rocking Objects",
    "Uncle Bob Touched Me",
    "Underpants Machine",
    "Universal Orgiastic Picnic",
    "The Urinals",
    "Urine Specimen",
    "Useless Pieces of Shit",
    "Vagina Dentata Organ",
    "Vaginal Blood Farts",
    "Vaginal Davis",
    "Vaginal Reference",
    "Van Gogh's Ear",
    "The Vast Void of Empty Nothingness",
    "The Vegas Cocks",
    "Vegetarian Meat",
    "Venus and the Razor Blades",
    "Vic Morrow's Head",
    "Virgin Prunes",
    "Virgin-Whore Complex",
    "Vermin from Venus",
    "The Veronica Cartwrights",
    "The Vibrators",
    "Vic Vaccume and the Attachments",
    "Violent Anal Death",
    "The Voluptuous Horror of Karen Black",
    "Vomit Launch",
    "The Vomit Spots",
    "Vomit Thrower",
    "Vomitorium",
    "Voodoo Meat Bucket",
    "Wafflebutt",
    "Waffles Against AIDS [Vafler mot AIDS]",
    "Walking With Edna",
    "Was I Naked",
    "Weird People in Giant Condoms",
    "Weird Skull Control",
    "The Well Hungarians",
    "Well Strung",
    "Wendy and Her Menstrual Cycles",
    "When People Were Shorter and Lived By the Water",
    "Where's The Pope?",
    "White People Lie",
    "White Trash Debutantes",
    "Whorehouse of Representatives",
    "Whorgasm",
    "Who The Hell Are You?",
    "Willie Nelson Mandela",
    "Wonderbred, the Refined White Flour Children",
    "Woodpussy",
    "Wrecked 'Em",
    "The Wrench Twisting Streetlickers",
    "Wynona Ryders",
    "The Yams from Outer Space",
    "The Yeasty Girls",
    "Your Damn Neighbors",
    "Your Naked Mother",
    "Zombies Under Stress",
    "Zoogz Rift and His Amazing Shitheads",
    "Zsa Zsa",
    "Zulu Leprechauns"
  ]
end
puts "Creating #{bands.count} bands"
bands.each do |band_name|
  band = Band.find_by_name(band_name) || Band.new
  band.name = band_name
  band.save
end

number_ratings_to_seed = use_clean_band_names ? 50 : 100
puts "Initializing #{number_ratings_to_seed}-ish random ratings for each user"
unless Rating.any?
  User.all.each do |user|
    number_ratings_to_seed.times do
      band = Band.find(rand(Band.count)+1)
      next if user.ratings.where(band_id: band.id).exists?
      user.ratings.create(band: band, score: (rand(5)+1))
    end
  end
end
